### PR TITLE
Enable Packit

### PR DESCRIPTION
**Pull request by olysonek**
https://packit.dev/

### CODE REVIEW

**Comment by olysonek** [comment]
@TomasTomecek Hi, any idea what the error means?

Note that I have the following in the SPEC:
```
Source1:  vsftpd.xinetd
Source2:  vsftpd.pam
Source3:  vsftpd.ftpusers
Source4:  vsftpd.user_list
Source6:  vsftpd_conf_migrate.sh
Source7:  vsftpd.service
Source8:  vsftpd@.service
Source9:  vsftpd.target
Source10: vsftpd-generator
```

So I copied those files from Fedora to this repo. Is that going to work?

**Comment by olysonek** [comment]
It looks like it fails on `git describe` because there are no tags in the repo.

**Comment by olysonek** [comment]
It looks like it fails on `git describe` because there are no tags in the repo.

**Comment by TomasTomecek** [comment]
yup, that's definitely the case - packit is using `git describe` to populate `Version` in the spec to get an accurate version string

you can set this up on your own easily by printing a static version string:
```yaml
current_version_command: [echo, "1.2.3"]
```
https://packit.dev/docs/configuration/

**Comment by olysonek** [comment]
> you can set this up on your own easily by printing a static version string:
> 
> ```yaml
> current_version_command: [echo, "1.2.3"]
> ```

That's a good idea. Thanks!

**Pull request closed without merging**
